# Generated by Django 3.0.8 on 2020-07-25 04:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('webapp', '0003_image_title'),
    ]

    operations = [
        migrations.AlterField(
            model_name='image',
            name='photo',
            field=models.ImageField(default='nophoto.png', upload_to='profile_pics'),
        ),
    ]
